### ISSUE TITLE
Bump plugin version

### ISSUE THREAD

**Issue by definitelyme** [Iteo/connecteo#20]
The plugin [connectivity_plus](https://pub.dev/packages/connectivity_plus/changelog) release a new version last month with some breaking changes. Do you plan upgrading this plugin to reflect changes to dependencies?

**Comment by kamilraczkaiteo** [comment]
Hello,

Thanks for your input. 🙏
Yes, the bump is scheduled on the next Monday. Once we do this, I will close the issue.
