### ISSUE TITLE
Bump connectivity_plus to latest version to avoid possible iOS crash

### ISSUE THREAD

**Issue by biklas7** [Iteo/connecteo#36]
This package still relies on version 4.0.2 of connectivity_plus, but as stated on the [changelog for 5.0.0](https://pub.dev/packages/connectivity_plus/changelog#500) that version is supposed to fix a crash that happens with builds on Xcode 15. Can we bump the version used with this package?

Release note from connectivity_plus 5.0.0:
BREAKING FIX(connectivity_plus): Bump min iOS to 12 to not crash after builds with Xcode 15 ([#2169](https://github.com/fluttercommunity/plus_plugins/issues/2169)). ([cf7d93fb](https://github.com/fluttercommunity/plus_plugins/commit/cf7d93fbfc76830acf2db755543cf4235a49df60))

**Comment by kamilraczka** [comment]
Hello!

Sorry for being late. You are absolutely right. We checked the changes which @alihassan143 did and they are fine. Once https://github.com/Iteo/connecteo/pull/37 get merged, we ship the updated version.

**Comment by alihassan143** [comment]
@kamilraczka  when this latest version will be published?

**Comment by kamilraczka** [comment]
@alihassan143 after merging [this one](https://github.com/Iteo/connecteo/pull/40), which happen very soon, we will ship the updated ver to the pub from the main branch (probably in the next hour or two)
