### ISSUE TITLE
[Feature]: Allow using hosts on mobile

### ISSUE THREAD

**Issue by anatoliisudor** [Iteo/connecteo#43]
### Problem

What is the logic of restricting addresses to be only IPs?
```dart
class DefaultHostReachabilityChecker implements HostReachabilityChecker {
...

  Future<bool> _canReachHost({
    required ConnectionEntry address,
    required Duration timeout,
  }) async {
    try {
      final socket = await Socket.connect(
        InternetAddress(address.host), // <<<----- Why do we have InternetAddress here???
...
``` 

### Desired Solution

`Socket.connect` can resolve both an IP and host, so simply passing worked for me.
```dart
final socket = await Socket.connect(
       address.host,
      _dnsPort,
``` 

Even if you don't want to "wait" until resolving the address by Socket, it's the developer's responsibility.
What if I want to use your library in the app, and I want to check only my own API URL in the mobile app?
Also _dnsPort then should be considered as an optional value

I can make a PR if you want

### On which platorm do you expect this solution?

iOS, Android

**Comment by kamilraczka** [comment]
Hello,

Thanks for your feedback. Answering your question - there is no crucial reason why we did force our host as the ip address on native platforms. It is a good suggestion to make it (both host and port) more customizable. 

We'll include it in the next version which we're working on right now and will be shipped very soon.

**Comment by anatoliisudor** [comment]
That's great news. Thanks a lot, and I will wait for the update! I am happy to see this is a more maintainable package since I came here to change internet_connection_checker, which has issues.
